---
  language: objective-c

  before_script:
    - brew update
    - brew install xctool

  script:
    - xctool -workspace 'Masonry.xcworkspace' -scheme 'Masonry' -configuration Debug -sdk iphonesimulator build test
